name: Statistics frontend Pipe

on:
  push:

  workflow_dispatch:

jobs:
  stage:
    name: Stats FE stage on server
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Docker Build and Stage
        run: docker-compose up -d --build
